DROP TABLE IF EXISTS ITEM_T;
DROP TABLE IF EXISTS USER_T;

CREATE TABLE IF NOT EXISTS USER_T (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING NOT NULL,
	EMAIL CHARACTER VARYING NOT NULL UNIQUE,
	CONSTRAINT USER_T_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ITEM_T (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING NOT NULL,
	DESCRIPTION CHARACTER VARYING NOT NULL,
	OWNER_ID BIGINT NOT NULL,
	AVAILABLE BOOLEAN NOT NULL,
	REQUEST_ID BIGINT,
	CONSTRAINT ITEM_T_PK PRIMARY KEY (ID),
	CONSTRAINT ITEM_T_FK FOREIGN KEY (OWNER_ID) REFERENCES USER_T(ID),
	CONSTRAINT ITEM_T_FK_1 FOREIGN KEY (REQUEST_ID) REFERENCES USER_T(ID)
);
